# Generated by Django 6.0.2 on 2026-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_age_student_birthday_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Technology Communication Management', 'Technology Communication Management')], max_length=100),
        ),
    ]
