# Generated by Django 6.0.2 on 2026-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Technology Communication Management', 'Technology Communication Management'), ('GENERAL', 'GENERAL')], default='GENERAL', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem')], default='1st Sem', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Technology Communication Management', 'Technology Communication Management')], max_length=100),
        ),
    ]
