# Generated by Django 6.0.2 on 2026-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_course_subject_semester_subject_year_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='max_units',
            field=models.IntegerField(default=1000),
        ),
    ]
