# Generated by Django 6.0.2 on 2026-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_student_max_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='max_units',
            field=models.IntegerField(default=50),
        ),
    ]
