# Generated by Django 6.0.2 on 2026-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_max_units'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
